FPU Instruction Support
pvk-2022-2/mips-emulator pull request #12
Opened 2022-01-26 15:21 UTC by eim64

Adds Instruction types and associated enums:
FPURType, FPUBType, FPUTType

These are made up names since I couldn't find any names in the
mips32 specification.

// FPURType is called so because it's similar to R type instructions
// FPUBType is called so because it does branching.
// FPUTType is called so because it (T)ransfers to and from the FPU

Checks get_type as well as some miscellanious instructions.

2022-01-27 13:26 UTC, antlilja requested changes
I would convert the Co processor static constexpr opcode values into an enum class. I would also either mask all the parameter values which are bigger than the bitfield field value they are assigned to, for example registers, fmt etc. Or I would use enum classes here as well, this way there is no possibility for a value that is too big (disregarding casts, you should probably mask the values anyway just to be safe).

2022-01-27 13:27 UTC, antlilja commented on include/mips-emulator/instruction.hpp
> +            fpu_rtype.fmt = static_cast<uint8_t>(op);
This parameter is larger than the field. Why is the parameter called op and the field called fmt?

2022-01-27 13:28 UTC, antlilja commented on include/mips-emulator/instruction.hpp
> +            fpu_btype.BC = static_cast<uint8_t>(op);
Larger param than field

2022-01-27 13:28 UTC, antlilja commented on include/mips-emulator/instruction.hpp
> +            fpu_rtype.ft = ft;
All register indices have larger params than fields

2022-01-27 13:28 UTC, antlilja commented on include/mips-emulator/instruction.hpp
> +            fpu_rtype.func = static_cast<uint8_t>(func);
larger param than field

2022-01-27 13:29 UTC, antlilja commented on include/mips-emulator/instruction.hpp
> +            fpu_ttype.CX = static_cast<uint8_t>(op);
CX field name but op param name?

2022-01-28 09:50 UTC, brynolv commented
Stop force-pushing, please! It becomes extremely difficult to see what you have actually changed if you do that, not to mention messing with the checksums and history (matters *less* in a PR, as they can be squashed+rebased+merged, but the principle of it is abuse of version control).

2022-02-01 12:35 UTC, antlilja approved these changes

2022-02-01 12:37 UTC, merged