SLT and SLTU instructions
pvk-2022-2/mips-emulator pull request #212
Opened 2022-02-15 14:43 UTC by hanstig

Added the slt and sltu instructions as well as some very basic tests for both.

2022-02-15 17:47 UTC, eim64 requested changes
Using outdated RegisterFile will not compile on main.

2022-02-17 16:18 UTC, hanstig commented
The issues should be fixed now

2022-02-17 19:29 UTC, eim64 requested changes
I recommend rebasing and force pusing so that only relevant commits remain. (no quick fix commits for instance) so that the commit history stays clean.

2022-02-17 19:29 UTC, eim64 commented on tests/executor.cpp
> +        using Address = typename RegisterFile::Unsigned;
Is Adress even used? if not, you should just get rid of this.

2022-02-19 12:14 UTC, hanstig commented
Unnecessary code removed, but I'm not sure how to force push and rebase in in order to fix the commit messages?

2022-02-19 13:11 UTC, eim64 approved these changes

2022-02-19 13:11 UTC, merged